config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root                'static_pages#home'
  get 'about'      => 'static_pages#about'
  get 'signup'     => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'recipes/search' => 'recipes#search'
  resources :users
  resources :recipes

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  require "httparty"
  require "uri"
  has_and_belongs_to_many :users
  validates :api_id, presence: true



  def self.search(ingredient, allergies)
    ingredient = URI.escape(ingredient)
    allergy = allergies.values
    allergies_params = []
    allergy.each do |a|
      allergies_params << URI.escape("allowedAllergy[]=#{a}")
    end

    comb_allergies=allergies_params.join('&')

    base_url = "http://api.yummly.com/v1/api/recipes"
    app_id = "a60a3813"
    app_key = "03a140c9f2bc94ab668e30a025477217"

    url = "#{base_url}?_app_id=#{app_id}&_app_key=#{app_key}"
    
    HTTParty.get ("#{url}&q=#{ingredient}&#{comb_allergies}")
    end



end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  require "httparty"
  # GET /recipes
  # GET /recipes.json
  def search
    @search_text = search_params[:q] || ''
    @allergy = params[:allergies]
    @search_result = Recipe.search(@search_text, @allergy) unless @search_text.empty? 
  end

  def index
    @recipes = []
    user_recipes = current_user.recipes
    user_recipes.each do |user_recipe|
      @recipes << get_recipe_from_api(user_recipe.api_id)
    end
  end

  def get_recipe_from_api(recipe_id)
    base_url = "http://api.yummly.com/v1/api/recipe"
    app_id = "a60a3813"
    app_key = "03a140c9f2bc94ab668e30a025477217"

    url = "#{base_url}/#{recipe_id}?_app_id=#{app_id}&_app_key=#{app_key}"
    HTTParty.get url
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit

  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)

    respond_to do |format|
      if @recipe.save
        current_user.recipes << @recipe
        format.html { redirect_to @recipe, notice: 'Recipe was successfully added.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:api_id)
    end

    def search_params
      params.permit(:q)
    end
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/recipes/_form.html.erb
<%= form_for(@recipe, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @recipe.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@recipe.errors.count, "error") %> prohibited this recipe from being saved:</h4>

      <ul>
      <% @recipe.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="page-header">
  <%= link_to recipes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @recipe, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Edit recipes</h1>
</div>

<%= render 'form' %>

app/views/recipes/index.html.erb
 <% provide(:title, 'Recipes') %>
 <div class="page-header">
    <h3>Your recipes</h3>
      <table class="table col-offset-md-4 col-md-8">
        <thead>
            <th></th>
            <th>Recipe Name:</th>
            <th>Total Time</th>
            <!-- <th>Calories per serving</th> -->
        </thead>


        <tbody>

            <% @recipes.each do |r|%>
            <tr>
             <td><img src='<%= r.parsed_response['images'][0]['hostedSmallUrl'] %>'></td>
             <td><a href="<%= r.parsed_response['attribution']['url'] %>"><%= r.parsed_response['name'] %></a></td>
             <td><%=r.parsed_response['totalTime']%></td>
             <!-- <td><%#=r.parsed_response['nutritionEstimates'][0]['value']%> calories</td> -->
            </tr>
             <% end%>

       </tbody>

     </table>

</div>

app/views/recipes/new.html.erb
<div class="page-header">
  <%= link_to recipes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New ingredient</h1>
</div>

<%= render 'form' %>

app/views/recipes/search.html.erb
<% provide(:title, 'Search') %>
<h1>What's in your kitchen cabinet? </h1>
<hr>
<div class ='col-md-3'>
  <h3>Search for recipes by ingredient:</h3>
  <hr>
  <%= form_tag("search", method: "get") do %>
    <%= label_tag(:q, "") %>
    <%= text_field_tag(:q, @search_text) %>
    <h4>Have an allergy? Let us remove those recipes for you.</h4>
    <%= check_box_tag("allergies[Dairy]", "396^Dairy-Free", params[:allergies].present? && params[:allergies][:Dairy].present?) %>
    <%= label_tag(:dairy, "Dairy") %>
    <br>
    <%= check_box_tag("allergies[Gluten]", "393^Gluten-Free", params[:allergies].present? &&params[:allergies][:Gluten].present?) %>
    <%= label_tag(:gluten, "Gluten") %>
    <!-- <br> -->
    <%#= check_box_tag("allergies[Peanut]", "Peanut-Free") %>
    <%#= label_tag(:peanut, "Peanut") %>
    <!-- <br>     -->
    <%#= check_box_tag("allergies[Tree-Nut]", "Tree nut-Free") %>
    <%#= label_tag(:treenut, "Tree nut") %>
    <%= submit_tag("Search") %>
  <% end %>

</div>

<div class = 'table-responsive col-md-offset-1 col-md-8'>
    <h3>Search Results for <%= @search_text %></h3>
      <table class="table col-md-12">
        <thead>
            <th></th>
            <th>Recipe Name:</th>
            <th>Rating:</th>
            <th>Total Time:</th>
            <th>Add to Favorites</th>
        </thead>
      <tbody>
      <% unless @search_result.nil? %>
        <% @search_result["matches"].each do |result| %>
        <tr>
          <td><%= image_tag result ["imageUrlsBySize"]["90"]%></td>
          <td><h4><%= result["recipeName"] %></h4></td>
          <td> <%= result["rating"] %></td>
          <td> <%= result["totalTimeInSeconds"]/60 %> minutes</td>
          <td><%= form_for(Recipe.new(api_id: result["id"])) do |f|%>
                <%= f.hidden_field :api_id, value: result["id"] %>
                <%= f.submit 'Add recipe'%>
              <% end %>
          </td>
          <% end %>
         <% end %>
       </tr>
      </tbody>
    </table>
</div>

app/views/recipes/show.html.erb
<div class="page-header">
  <%= link_to recipes_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_recipe_path(@recipe), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show Recipe</h1>
  <td><%= link_to 'Delete',@recipe, method: :delete, data: {confirm: "Are you sure you want to remove this recipe?"}%></td>
</div>