config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root                'static_pages#home'
  get 'about'      => 'static_pages#about'
  get 'signup'     => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'recipes/search' => 'recipes#search'
  resources :users
  resources :recipes

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small class = "footer-brand">
    Residual Fare | &copy <%= link_to 'Loren Crawford', 'http://lorencrawford.branded.me/' %>
  </small>
  <!-- <nav>
    <ul>
      <li><%= link_to 'About', about_path %></li>
      <li><%= link_to "Sign Up", signup_path %></li>
      <li><%= link_to "Log In", login_path %></li>

    </ul>
  </nav> -->
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
    <div>
      <%= link_to "Residual Fare", root_path, id: "logo" %>
      <!-- <i class="fa fa-spoon"></i> -->
      </div>
      <nav>
        <ul class="nav navbar-nav navbar-right " id = "custom-nav">
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'About', about_path %></li>
          <!-- <li><%= link_to "Log In", login_path %></li> -->
          <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu" id = 'custom-dropdown'>
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Recipes", recipes_path%></li>
              <li><%= link_to "Search ingredients", recipes_search_path %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
          <li><%= link_to "Get started", signup_path, class: "btn btn-xlarge btn-info", id:"get-started"%></li>
        <% end %>
        </ul>
      </nav>
    </div>
  </nav>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_shim.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Loren Crawford">
  <title><%= yield(:title) %> | Residual Fare</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body id ='wrapper' class = 'background-image'>
  <%= render 'layouts/shim' %>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

    <%= yield %>


  </div>
    <%= render 'layouts/footer' %>
</body>
</html>